// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUALpxv-NUQv41a3wYNlLFhpna3JUkdQ',
    appId: '1:810092682000:web:9c4e9b657309afdf876395',
    messagingSenderId: '810092682000',
    projectId: 'halalhubmobile',
    authDomain: 'halalhubmobile.firebaseapp.com',
    storageBucket: 'halalhubmobile.firebasestorage.app',
    measurementId: 'G-1SD309XKMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWh0pSOiMJh3qdBNuotjf4hem_fZONTMo',
    appId: '1:810092682000:android:27a23abdfcd0dc12876395',
    messagingSenderId: '810092682000',
    projectId: 'halalhubmobile',
    storageBucket: 'halalhubmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4IlZWzq-iYwn91F-kd5sQAQ-2GxVjTw',
    appId: '1:810092682000:ios:ac37917643e844f0876395',
    messagingSenderId: '810092682000',
    projectId: 'halalhubmobile',
    storageBucket: 'halalhubmobile.firebasestorage.app',
    androidClientId: '810092682000-dkgiicquf5v0efqkgjnv68b2a61mejtj.apps.googleusercontent.com',
    iosClientId: '810092682000-liakbc4u6tt8f0q1g6ne61obthrsd6pv.apps.googleusercontent.com',
    iosBundleId: 'com.infonex.halalhubrestu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx4IlZWzq-iYwn91F-kd5sQAQ-2GxVjTw',
    appId: '1:810092682000:ios:0d37f7143246f647876395',
    messagingSenderId: '810092682000',
    projectId: 'halalhubmobile',
    storageBucket: 'halalhubmobile.firebasestorage.app',
    androidClientId: '810092682000-dkgiicquf5v0efqkgjnv68b2a61mejtj.apps.googleusercontent.com',
    iosClientId: '810092682000-rqphs2um46idq38as9brp9gk5rcd8mcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalHubResto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUALpxv-NUQv41a3wYNlLFhpna3JUkdQ',
    appId: '1:810092682000:web:bec66ded7fa097c4876395',
    messagingSenderId: '810092682000',
    projectId: 'halalhubmobile',
    authDomain: 'halalhubmobile.firebaseapp.com',
    storageBucket: 'halalhubmobile.firebasestorage.app',
    measurementId: 'G-T4V6JYGK98',
  );
}
