import 'package:flutter/material.dart';
import 'package:halalhub_restaurant/core/extensions/size_extension.dart';

abstract class AppTextStyle {
  static TextStyle _base(double fontSize, {required FontWeight fontWeight, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => TextStyle(fontSize: fontSize, fontWeight: fontWeight, fontFamily: 'Inter', color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  static double _size(BuildContext context, double px, double? aW) => aW != null ? context.spOf(px, aW) : context.sp(px);

  // 10px
  static TextStyle regular10(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 10, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium10(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 10, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold10(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 10, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold10(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 10, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 12px
  static TextStyle regular12(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 12, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium12(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 12, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold12(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 12, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold12(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 12, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 14px
  static TextStyle regular14(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 14, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium14(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 14, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold14(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 14, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold14(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 14, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 16px
  static TextStyle regular16(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 16, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium16(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 16, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold16(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 16, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold16(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 16, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 18px
  static TextStyle regular18(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 18, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium18(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 18, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold18(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 18, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold18(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 18, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 20px
  static TextStyle regular20(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 20, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium20(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 20, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold20(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 20, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold20(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 20, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 22px
  static TextStyle regular22(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 22, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium22(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 22, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold22(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 22, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold22(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 22, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 24px
  static TextStyle regular24(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 24, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium24(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 24, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold24(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 24, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold24(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 24, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 26px
  static TextStyle regular26(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 26, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium26(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 26, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold26(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 26, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold26(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 26, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 28px
  static TextStyle regular28(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 28, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium28(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 28, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold28(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 28, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold28(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 28, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 30px
  static TextStyle regular30(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 30, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium30(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 30, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold30(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 30, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold30(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 30, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);

  // 32px
  static TextStyle regular32(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 32, aW), fontWeight: FontWeight.w400, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle medium32(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 32, aW), fontWeight: FontWeight.w500, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle semibold32(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 32, aW), fontWeight: FontWeight.w600, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
  static TextStyle bold32(BuildContext context, {double? aW, double? size, Color? color, TextOverflow? overflow, TextDecoration? decoration, Color? decorationColor}) => _base(size ?? _size(context, 32, aW), fontWeight: FontWeight.w700, color: color, overflow: overflow, decoration: decoration, decorationColor: decorationColor);
}
